import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { LogOut, PackageCheck, UserRound } from 'lucide-react';
import { api, User } from '../api/client';
import { useRealtimeRefresh } from '../lib/realtime';

type CustomerOrder = { id: string; orderNumber: string; status: string; createdAt: string; deliveryMethod?: string; preferredDate?: string; staffNotes?: string; items: Array<{ id: string; productName: string; quantity: number }> };
const statusLabel = (status: string) => status.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function CustomerAccount() {
  const [mode, setMode] = useState<'register' | 'login'>('register');
  const [user, setUser] = useState<User | null>(null); const [orders, setOrders] = useState<CustomerOrder[]>([]);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [params] = useSearchParams(); const navigate = useNavigate();
  const loadAccount = async () => { try { const [account, history] = await Promise.all([api<User>('/auth/me'), api<CustomerOrder[]>('/orders/mine')]); setUser(account.data); setOrders(history.data ?? []); } catch { setUser(null); } };
  useEffect(() => { void loadAccount(); }, []);
  useRealtimeRefresh(loadAccount);
  useEffect(() => { if (params.get('order') === 'received') setNotice('Your order request was received. Staff will review it and update its status here.'); }, [params]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); try { await api(mode === 'register' ? '/auth/register' : '/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); await loadAccount(); window.dispatchEvent(new Event('natgas-auth-change')); navigate(params.get('next') ?? '/account', { replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to continue.'); } };
  const saveProfile = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); try { const result = await api<User>('/auth/profile', { method: 'PUT', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); setUser(result.data); setNotice(result.message ?? 'Account details updated.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save account details.'); } };
  const changePassword = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); try { const result = await api('/auth/change-password', { method: 'PUT', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); event.currentTarget.reset(); setNotice(result.message ?? 'Password changed.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to change password.'); } };
  const logout = async () => { try { await api('/auth/logout', { method: 'POST' }); } finally { setUser(null); setOrders([]); window.dispatchEvent(new Event('natgas-auth-change')); setNotice('You have been signed out.'); navigate('/account', { replace: true }); } };

  if (!user) return <section className="section"><div className="account-box admin-card admin-card-body"><span className="chip-sm">CUSTOMER ACCOUNT</span><h1>{mode === 'register' ? 'Create your order account' : 'Welcome back'}</h1><p>Sign in securely to submit LPG order requests and receive confirmation updates.</p><div className="jobs-tabs"><button type="button" className={`jobs-tab ${mode === 'register' ? 'active' : ''}`} onClick={() => setMode('register')}>Create account</button><button type="button" className={`jobs-tab ${mode === 'login' ? 'active' : ''}`} onClick={() => setMode('login')}>Sign in</button></div><form className="order-form" onSubmit={submit}>{error && <p className="form-err">{error}</p>}{notice && <p className="form-ok">{notice}</p>}{mode === 'register' && <><label>First name<input required name="firstName" /></label><label>Last name<input required name="lastName" /></label><label>Phone number<input required name="phone" /></label></>}<label>Email address<input required type="email" name="email" /></label><label>Password<input required type="password" name="password" minLength={8} /></label><button className="btn btn-primary">{mode === 'register' ? 'Create account and continue' : 'Sign in and continue'}</button></form></div></section>;

  return <section className="section customer-account-section"><div className="wrap"><div className="customer-account-head"><div><span className="chip-sm">MY NATGAS ACCOUNT</span><h1>Hello, {user.firstName}.</h1><p>View your orders, confirmation updates and account details in one place.</p></div><div><Link className="btn btn-outline" to="/products"><PackageCheck size={15} /> Order gas</Link><button className="btn btn-dark" onClick={logout}><LogOut size={15} /> Sign out</button></div></div>{notice && <p className="form-ok">{notice}</p>}{error && <p className="form-err">{error}</p>}<div className="customer-account-grid"><div className="customer-orders"><h2>Your order requests</h2>{orders.length ? orders.map((order) => <article className="customer-order-card" key={order.id}><div><span className={`status-pill ${order.status.toLowerCase()}`}>{statusLabel(order.status)}</span><h3>{order.orderNumber}</h3><p>Placed {new Date(order.createdAt).toLocaleDateString()} · {order.deliveryMethod === 'PICKUP' ? 'Outlet collection' : 'Delivery'}</p></div><div className="customer-order-items">{order.items.map((item) => <span key={item.id}>{item.quantity} × {item.productName}</span>)}</div>{order.preferredDate && <small>Preferred date: {new Date(order.preferredDate).toLocaleDateString()}</small>}{order.staffNotes && <div className="customer-order-note"><b>Message from NATGAS</b><p>{order.staffNotes}</p></div>}</article>) : <div className="empty-state customer-empty"><UserRound size={28} /><h3>No orders yet</h3><p>When staff confirm an LPG order, its progress will appear here.</p><Link className="btn btn-primary" to="/products">Browse products</Link></div>}</div><aside className="customer-account-controls"><form className="admin-card admin-card-body order-form" onSubmit={saveProfile}><h2>Account details</h2><label>First name<input required name="firstName" defaultValue={user.firstName} /></label><label>Last name<input required name="lastName" defaultValue={user.lastName} /></label><label>Phone number<input required name="phone" defaultValue={user.phone ?? ''} /></label><label>Email address<input value={user.email} disabled /></label><button className="btn btn-primary">Save details</button></form><form className="admin-card admin-card-body order-form" onSubmit={changePassword}><h2>Change password</h2><label>Current password<input required type="password" name="currentPassword" /></label><label>New password<input required type="password" minLength={8} name="newPassword" /></label><label>Confirm new password<input required type="password" minLength={8} name="confirmPassword" /></label><button className="btn btn-outline">Update password</button></form></aside></div></div></section>;
}
