import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, User } from '../api/client';
import { CartItem, getCart, saveCart } from '../lib/cart';

export default function OrderCart() {
  const [cart, setCart] = useState<CartItem[]>(getCart()); const [user, setUser] = useState<User | null>(null); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { api<User>('/auth/me').then(r => setUser(r.data)).catch(() => undefined); }, []);
  const update = (id: string, quantity: number) => { const next = cart.map(item => item.id === id ? { ...item, quantity: Math.max(1, quantity) } : item); setCart(next); saveCart(next); };
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const fd = new FormData(e.currentTarget); const date = String(fd.get('preferredDate') ?? ''); try { await api('/orders', { method:'POST', body:JSON.stringify({ items:cart.map(item => ({ productId:item.id, quantity:item.quantity })), deliveryAddress:fd.get('deliveryAddress'), district:fd.get('district'), phone:fd.get('phone'), deliveryMethod:fd.get('deliveryMethod'), preferredDate:date ? new Date(`${date}T09:00:00`).toISOString() : undefined, notes:fd.get('notes') }) }); saveCart([]); setCart([]); navigate('/'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to submit order'); } };
  if (!cart.length) return <section className="section"><div className="wrap empty-state"><h2>Your order list is empty</h2><Link className="btn btn-primary" to="/products">Browse products</Link></div></section>;
  return <section className="section"><div className="wrap order-wrap"><div><span className="chip-sm">ORDER REQUEST</span><h1>Review your LPG order</h1>{cart.map(item => <div className="order-line" key={item.id}>{item.imageUrl && <img src={item.imageUrl} alt=""/>}<div><b>{item.name}</b><small>{item.cylinderSize}</small></div><input type="number" min="1" value={item.quantity} onChange={e => update(item.id, Number(e.target.value))}/><button onClick={() => { const next=cart.filter(x=>x.id!==item.id); setCart(next); saveCart(next); }}>Remove</button></div>)}</div>{user ? <form className="admin-card admin-card-body order-form" onSubmit={submit}><h2>Delivery details</h2>{error && <p className="form-err">{error}</p>}<label>Fulfilment method<select name="deliveryMethod"><option value="DELIVERY">Home / business delivery</option><option value="PICKUP">Collect from a NATGAS outlet</option></select></label><label>Delivery address<input required name="deliveryAddress"/></label><label>District<input required name="district"/></label><label>Preferred date<input type="date" name="preferredDate" min={new Date().toISOString().slice(0,10)}/></label><label>Phone number<input required name="phone" defaultValue={user.phone ?? ''}/></label><label>Notes<textarea name="notes" placeholder="Landmark, preferred time or any delivery instructions"/></label><button className="btn btn-primary">Submit order request</button></form> : <div className="admin-card admin-card-body"><h2>Sign in to submit</h2><p>Create a customer account or sign in before staff can confirm your order.</p><Link className="btn btn-primary" to="/account?next=/order">Create account / sign in</Link></div>}</div></section>;
}
