import { FormEvent, useEffect, useRef, useState } from 'react';
import { RotateCcw, Save } from 'lucide-react';
import { api } from '../../api/client';
type Values = Record<string, string>;
const defaults: Values = { home_hero_media_url:'', home_hero_media_type:'image', home_hero_overlay:'70', home_announcement_enabled:'false', home_announcement_label:'New', home_announcement_text:'', home_announcement_link:'', site_font:'Inter' };
export default function AdminExperience(){
 const [v,setV]=useState<Values>(defaults),[file,setFile]=useState<File|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');const ref=useRef<HTMLInputElement>(null);const set=(k:string,x:string)=>setV(s=>({...s,[k]:x}));
 useEffect(()=>{api<Values>('/settings/public').then(r=>setV(s=>({...s,...Object.fromEntries(Object.entries(r.data??{}).map(([k,x])=>[k,String(x??'')]))}))).catch(()=>undefined)},[]);
 const save=async(e:FormEvent)=>{e.preventDefault();try{let url=v.home_hero_media_url,type=v.home_hero_media_type;if(file){const f=new FormData();f.append('file',file);f.append('folder','homepage');const r=await api<{url:string}>('/admin/media/upload',{method:'POST',body:f,headers:{}});url=r.data.url;type=file.type.startsWith('video/')?'video':'image';}const next={...v,home_hero_media_url:url,home_hero_media_type:type};await Promise.all(Object.entries(next).map(([key,value])=>api(`/admin/settings/${key}`,{method:'PUT',body:JSON.stringify({value,type:'string',category:'experience'})})));setV(next);setNotice('Site experience published.');}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}};
 const restore=async()=>{if(!confirm('Restore visual defaults? Content, users, orders and products will not change.'))return;try{const r=await api('/admin/settings/restore-defaults',{method:'POST'});setV(defaults);setNotice(r.message??'Defaults restored.');}catch(e){setError(e instanceof Error?e.message:'Unable to restore.')}};
 return <div><div className="admin-page-head"><div><h1 className="admin-page-title">Site experience</h1><p className="admin-page-sub">Homepage visual, fast flyer, font and recovery controls.</p></div></div>{notice&&<p className="form-ok">{notice}</p>}{error&&<p className="form-err">{error}</p>}<form className="admin-form" onSubmit={save}><section className="admin-card admin-card-body"><h2>Homepage background</h2><div className="form-grid"><label>Image or video<input ref={ref} type="file" accept="image/*,video/mp4,video/webm" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Media URL<input value={v.home_hero_media_url} onChange={e=>set('home_hero_media_url',e.target.value)}/></label><label>Overlay darkness {v.home_hero_overlay}%<input type="range" min="15" max="90" value={v.home_hero_overlay} onChange={e=>set('home_hero_overlay',e.target.value)}/></label></div></section><section className="admin-card admin-card-body"><h2>Announcement flyer</h2><div className="form-grid"><label>Visible<select value={v.home_announcement_enabled} onChange={e=>set('home_announcement_enabled',e.target.value)}><option value="false">Hidden</option><option value="true">Visible</option></select></label><label>Label<input value={v.home_announcement_label} onChange={e=>set('home_announcement_label',e.target.value)}/></label><label>Message<input value={v.home_announcement_text} onChange={e=>set('home_announcement_text',e.target.value)}/></label><label>Link<input value={v.home_announcement_link} onChange={e=>set('home_announcement_link',e.target.value)}/></label></div></section><section className="admin-card admin-card-body"><h2>Typography</h2><label>Site font<select value={v.site_font} onChange={e=>set('site_font',e.target.value)}><option>Inter</option><option>Arial</option><option>Georgia</option></select></label></section><div className="admin-form-actions"><button type="button" className="btn btn-outline" onClick={restore}><RotateCcw size={15}/> Restore visual defaults</button><button className="btn btn-primary"><Save size={15}/> Publish changes</button></div></form></div>;
}
